version: 2
project_name: phonenumberwin
builds:
  -
    id: "drawphonegui"
    binary: "drawphonegui"
    dir: cmd/drawphonegui
    env:
      - CGO_ENABLED=0
    goos:
      - windows
    goarch:
      - amd64
archives:
  -
    format_overrides:
      - goos: windows
        formats:
          - zip
checksum:
  name_template: 'checksums-win.txt'
snapshot:
  version_template: "{{ .Tag }}-next"
changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'

brews:
  -
    repository:
      owner: arran4
      name: homebrew-tap
      token: "{{ .Env.TAP_GITHUB_TOKEN }}" # From Secrets.TAP_GITHUB_TOKEN update ci.yaml too to match
    branch: "{{.ProjectName}}-{{.Version}}"
    pull_request:
      enabled: true
      draft: false
